unique_ids:
  assets:
    standard-page.html: 33NVMHJK6SN5RQ4QZWTQOTJI72O74DMM
    theme.css: VFLAGTXQWTEFQABY5N57Y5QFF5DZ5SVN
  forms:
    Form1: 7YLLETHYJ3BNQUF4XFOAYP5HKZ2Y7NOK
  modules: {}
  scripts: {}
  server_modules: {}
